basePath: /svr
definitions:
  internal.HelloRsp:
    properties:
      greet:
        type: string
    type: object
host: localhost:8086
info:
  contact:
    email: sinuxlee@qq.com
    name: sinuxlee
    url: http://www.swagger.io/support
  description: 项目结构概要描述
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: template
  version: "1.0"
paths:
  /v1/hello/{name}:
    get:
      consumes:
      - application/json
      description: |-
        这里写一大段描述
        还支持多行
      parameters:
      - default: libz
        description: 昵称
        in: path
        name: name
        required: true
        type: string
      - default: "1001"
        description: 区服编号
        in: query
        name: code
        required: true
        type: string
      - default: application/json
        description: 数据格式
        in: header
        name: Content-Type
        required: true
        type: string
      - description: 测试数据
        in: body
        name: body
        required: true
        schema:
          allOf:
          - type: object
          - properties:
              age:
                type: integer
              name:
                type: string
            type: object
      produces:
      - application/json
      responses:
        "200":
          description: 响应体
          schema:
            allOf:
            - type: object
            - properties:
                code:
                  type: integer
                data:
                  $ref: '#/definitions/internal.HelloRsp'
                message:
                  type: string
              type: object
      summary: 问候
      tags:
      - Hello
schemes:
- http
- https
securityDefinitions:
  BasicAuth:
    type: basic
  TokenAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: 各种问候
  name: Hello
x-extension-openapi:
  example: value on a json format
